cloud:
  aws:
    credentials:
      access-key: your-access-key
      secret-key: your-secret-key
    region:
      static: ap-south-1
    stack:
      auto: false
 
application:   
  bucket:
    name: java.aws.project
    
server:
  port: 7070
      
